version: "2"
services:
  nginx:
    restart: "always"
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/1.crt:/etc/nginx/1.crt
      - ./conf/2.key:/etc/nginx/2.key
      - /home/yzxy:/etc/nginx/yzxy
      - ./shopbarcode:/etc/nginx/shopbarcode/shopbarcode
    ports:
      - "80:80"
      - "443:443"
    network_mode: "host"
  redis:
    image: redis
    volumes:
      - "./redis_data:/data"
    command: redis-server --requirepass tzh1234567890
    ports:
      - "6379:6379"
    network_mode: "host"


